<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="A2ML30049" ignored="0" name="E2E Tests" tests="4" failures="2" timestamp="03 Jun 2019 10:55:21 GMT" time="206.033" errors="0">
  <testcase name="@AfterClass dbCleanUp" time="133.122" classname="io.mosip.e2e.tests.RegistrationProcessor">
    <failure type="org.hibernate.exception.SQLGrammarException" message="could not execute statement">
      <![CDATA[org.hibernate.exception.SQLGrammarException: could not execute statement
at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106)
at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:178)
at org.hibernate.engine.query.spi.NativeSQLQueryPlan.performExecuteUpdate(NativeSQLQueryPlan.java:107)
at org.hibernate.internal.SessionImpl.executeNativeUpdate(SessionImpl.java:1606)
at org.hibernate.query.internal.NativeQueryImpl.doExecuteUpdate(NativeQueryImpl.java:295)
at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1618)
at io.mosip.dao.RegProcDBCleanUp.deleteFromRegProcTables(RegProcDBCleanUp.java:33)
at io.mosip.dao.RegProcDBCleanUp.prepareQueryList(RegProcDBCleanUp.java:58)
at io.mosip.e2e.tests.RegistrationProcessor.dbCleanUp(RegistrationProcessor.java:29)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "regprc.reg_uin" does not exist
  Position: 13
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
... 33 more
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass dbCleanUp -->
  <testcase name="" time="0.013" classname="io.mosip.e2e.tests.RegistrationProcessor"/>
  <testcase name="E2E_RegistrationProcessor_getPackets" time="26.461" classname="io.mosip.e2e.tests.RegistrationProcessor"/>
  <testcase name="E2E_RegistrationProcessor_syncPacket" time="6.235" classname="io.mosip.e2e.tests.RegistrationProcessor">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at io.mosip.e2e.tests.RegistrationProcessor.uploadPacket(RegistrationProcessor.java:53)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- E2E_RegistrationProcessor_syncPacket -->
  <testcase name="E2E_RegistrationProcessor_uploadPacket" time="40.153" classname="io.mosip.e2e.tests.RegistrationProcessor">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at io.mosip.e2e.tests.RegistrationProcessor.compareDbTransactions(RegistrationProcessor.java:61)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- E2E_RegistrationProcessor_uploadPacket -->
</testsuite> <!-- E2E Tests -->
